Algoritmo "exercicio32"
// Faça um algoritmo que leia um número inteiro qualquer e imprima na tela
//a tabuada do respetivo número lido.
Var
   i, num: inteiro

Inicio
      escreva("Informe um número para apresentar sua respectiva tabuada: ")
      leia(num)
      
      para i de 1 ate 10 faca
           escreva(num)
           escreva(" x")
           escreva(i)
           escreva(" =")
           escreval(num*i)
      fimpara

Fimalgoritmo